adminapp/urls.py
from django.urls import path

from adminapp.views import index, UserListView, UserCreateView, UserUpdateView, UserDeleteView, ProductCategoryList, \
    ProductCategoryUpdate, ProductCategoryDelete

app_name = 'adminapp'

urlpatterns = [
    path('', index, name='index'),
    path('users/', UserListView.as_view(), name='admin_users'),
    path('users-create/', UserCreateView.as_view(), name='admin_users_create'),
    path('users-update/<int:pk>/', UserUpdateView.as_view(), name='admin_users_update'),
    path('users-delete/<int:pk>/', UserDeleteView.as_view(), name='admin_users_delete'),
    path('categories/', ProductCategoryList.as_view(), name='admin_categories_list'),
    path('category/update/<int:pk>/', ProductCategoryUpdate.as_view(), name='admin_category_update'),
    path('category/delete/<int:pk>/', ProductCategoryDelete.as_view(), name='admin_category_delete'),
]

authapp/urls.py
from django.urls import path

from authapp.views import Login, RegisterView, Logout, ProfileEdit

app_name = 'authapp'

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileEdit.as_view(), name='profile'),
    path('logout/', Logout.as_view(), name='logout'),
    path('verify/<str:email>/<str:activation_key>/', RegisterView.verify, name='verify'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from mainapp.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('baskets/', include('basketapp.urls', namespace='baskets')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
    path('admin-staff/', include('adminapp.urls', namespace='admin_staff')),
    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
   import debug_toolbar

   urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms

from authapp.forms import UserRegisterForm, UserEditForm
from authapp.models import User
from mainapp.models import ProductCategory, Product


class UserAdminRegistrationForm(UserRegisterForm):
    avatar = forms.ImageField(widget=forms.FileInput(), required=False)

    class Meta:
        model = User
        fields = ('username', 'email', 'avatar', 'first_name', 'last_name', 'password1', 'password2', 'age')

    def __init__(self, *args, **kwargs):
        super(UserAdminRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['avatar'].widget.attrs['class'] = 'custom-file-input'


class UserAdminProfileForm(UserEditForm):

    def __init__(self, *args, **kwargs):
        super(UserAdminProfileForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['readonly'] = False
        self.fields['email'].widget.attrs['readonly'] = False


class ProductCategoryEditForm(forms.ModelForm):
    discount = forms.IntegerField(label='скидка', required=False, min_value=0, max_value=90, initial=0)

    class Meta:
        model = ProductCategory
        #fields = '__all__'
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(ProductCategoryEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductEditForm(forms.ModelForm):
    discount = forms.IntegerField(label='скидка', required=False, min_value=0, max_value=90, initial=0)

    class Meta:
        model = Product
        fields = '__all__'
        # exclude = ()

    def __init__(self, *args, **kwargs):
        super(ProductEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

adminapp/views.py
from django.db import connection
from django.db.models import F
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse_lazy
from django.contrib.auth.decorators import user_passes_test
from django.utils.decorators import method_decorator
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from authapp.models import User
from adminapp.forms import UserAdminRegistrationForm, UserAdminProfileForm, ProductCategoryEditForm
from django.contrib.auth.mixins import LoginRequiredMixin

# FBV = Function-Based-View
# CBV = Class-Based-View
from mainapp.models import ProductCategory


@user_passes_test(lambda u: u.is_superuser, login_url='/')
def index(request):
    return render(request, 'adminapp/index.html')


# READ
class UserListView(LoginRequiredMixin, ListView):
    model = User
    template_name = 'adminapp/admin-users-read.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser, login_url='/'))
    def dispatch(self, request, *args, **kwargs):
        return super(UserListView, self).dispatch(request, *args, **kwargs)


# CREATE
class UserCreateView(CreateView):
    model = User
    template_name = 'adminapp/admin-users-create.html'
    form_class = UserAdminRegistrationForm
    success_url = reverse_lazy('admin_staff:admin_users')


# UPDATE
class UserUpdateView(UpdateView):
    model = User
    template_name = 'adminapp/admin-users-update-delete.html'
    form_class = UserAdminProfileForm
    success_url = reverse_lazy('admin_staff:admin_users')

    def get_context_data(self, **kwargs):
        context = super(UserUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'GeekShop - Редактирование пользователя'
        return context


# DELETE
class UserDeleteView(DeleteView):
    model = User
    template_name = 'adminapp/admin-users-update-delete.html'
    success_url = reverse_lazy('admin_staff:admin_users')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class ProductCategoryList(ListView):
    """
    Контроллер вывода списка категорий
    """
    model = ProductCategory
    template_name = 'adminapp/category_list.html'


class ProductCategoryUpdate(UpdateView):
    """
    Контроллер обновления информациия в существующей категории
    """
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('admin_staff:index')
    form_class = ProductCategoryEditForm
    context_object_name = 'category'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'категории/редактирование'
        return context

    def form_valid(self, form):
        if 'discount' in form.cleaned_data:
            discount = form.cleaned_data['discount']
            if discount:
                print(f'применяется скидка {discount}% к товарам категории {self.object.name}')
                self.object.product_set.update(price=F('price') * (1 - discount / 100))
                db_profile_by_type(self.__class__, 'UPDATE', connection.querues)


class ProductCategoryDelete(DeleteView):

    """Контроллер для удаления категорий
    метод: delete - переопределен дабы не удалять из системы объекты, а просто их делать не активными.
    """
    model = ProductCategory
    success_rul = reverse_lazy('admin_staff:index')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())

adminapp/templates/adminapp/admin-users-create.html
{% extends 'adminapp/index.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Создание пользователя</h1>
        <form action="{% url 'admin_staff:admin_users_create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                        {{ form.first_name }}
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                        {{ form.last_name }}
                    </div>
                </div>
            </div>
            <div class="form-row mb-2">
                <div class="col-lg-12">
                    <div class="custom-file">
                        {{ form.avatar }}
                        <label class="custom-file-label" for="{{ form.avatar.id_for_label }}">Выберите
                            изображение</label>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="col-lg-6">
                    <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                    {{ form.username }}
                </div>
                <div class="col-lg-6">
                    <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                        почты</label>
                    {{ form.email }}
                </div>
            </div>
            <div class="form-row">
                <div class="col-lg-6">
                    <label class="small mb-1" for="{{ form.password1.id_for_label }}">Пароль</label>
                    {{ form.password1 }}
                </div>
                <div class="col-lg-6">
                    <label class="small mb-1" for="{{ form.password2.id_for_label }}">Повторите пароль</label>
                    {{ form.password2 }}
                </div>
            </div>
            <div class="form-row">
                <div class="col-lg-12" style="margin-top: 33px;">
                    <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                </div>
            </div>
        </form>
    </div>
</main>
{% endblock %}

adminapp/templates/adminapp/admin-users-read.html
{% extends 'adminapp/index.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Пользователи</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Пользователи
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Адрес эл. почты</th>
                            <th>Персонал сайта</th>
                            <th>Активный</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Адрес эл. почты</th>
                            <th>Персонал сайта</th>
                            <th>Активный</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for user in object_list %}
                            <tr>
                                <td><a href="{% url 'admin_staff:admin_users_update' user.id %}" style="color: dodgerblue">{{ user.username }}</a></td>
                                <td>{{ user.first_name }}</td>
                                <td>{{ user.last_name }}</td>
                                <td>{{ user.email }}</td>
                                <td class="text-center">
                                    {% if user.is_staff %}
                                        <i class="fas fa-check-circle"></i>
                                    {% else %}
                                        <i class="fas fa-times-circle"></i>
                                    {% endif %}
                                </td>
                                <td class="text-center">
                                    {% if user.is_active %}
                                        <i class="fas fa-check-circle"></i>
                                    {% else %}
                                        <i class="fas fa-times-circle"></i>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'adminapp:admin_users_create' %}">
                    <button class="btn btn-success">Создать пользователя</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}

adminapp/templates/adminapp/admin-users-update-delete.html
{% extends 'adminapp/index.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Редактирование пользователя | {{ user.username }}</h1>
        <div class="card-body">
            <form action="{% url 'admin_staff:admin_users_update' user.id %}" method="post"
                  enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                            {{ form.first_name }}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                            {{ form.last_name }}
                        </div>
                    </div>
                </div>
                <div class="form-row mb-2">
                    <div class="col-lg-12">
                        <div class="custom-file">
                            {{ form.avatar }}
                            <label class="custom-file-label" for="{{ form.avatar.id_for_label }}">Выберите
                                изображение</label>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя
                            пользователя</label>
                        {{ form.username }}
                    </div>
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                            почты</label>
                        {{ form.email }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
            <div class="row">
                <div class="col-lg-12" style="margin-top: 33px;">
                    <form action="{% url 'admin_staff:admin_users_delete' user.id %}" method="post">
                        {% csrf_token %}
                        <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

adminapp/templates/adminapp/category_list.html
{% extends 'adminapp/index.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Категории</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Категории
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Название</th>
                            <th>Скидка</th>
                            <th>Активный</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Название</th>
                            <th>Скидка</th>
                            <th>Активный</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for elem in object_list %}
                            <tr>
                                <td><a href="{% url 'admin_staff:admin_category_update' elem.pk %}" style="color: dodgerblue">{{ elem.name }}</a></td>
                                <td>{{ elem.discount }}</td>

                                <td class="text-center">
                                    {% if elem.is_active %}
                                        <i class="fas fa-check-circle"></i>
                                    {% else %}
                                        <i class="fas fa-times-circle"></i>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{#% url 'admin_staff:admin_users_create' %#}">
                    <button class="btn btn-success">+ Добавить</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}

adminapp/templates/adminapp/category_update.html
{% extends 'adminapp/index.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Редактирование категории | {{ category.name }}</h1>
        <div class="card-body">
            <form action="{% url 'admin_staff:admin_category_update' 1 %}" method="post"
                  enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.name.id_for_label }}">Название</label>
                            {{ form.name }}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.discount.id_for_label }}">Скидка</label>
                            {{ form.discount }}
                        </div>
                    </div>
                </div>

                <div class="form-row">
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.is_active.id_for_label }}">Активная</label>
                        {{ form.is_active }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
            <div class="row">
                <div class="col-lg-12" style="margin-top: 33px;">
                    <form action="{#% url 'admin_staff:admin_category_delete' category.id %#}" method="post">
                        {% csrf_token %}
                        <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

adminapp/templates/adminapp/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>GeekShop - Admin</title>
    <link href="{% static 'css/auth-admin.css' %}" rel="stylesheet"/>
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet"
          crossorigin="anonymous"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'index' %}">GeekShop</a>
    <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i>
    </button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Поиск..." aria-label="Search"
                   aria-describedby="basic-addon2"/>
            <div class="input-group-append">
                <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
            </div>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'auth:logout' %}">Logout</a>
            </div>
        </li>
    </ul>
</nav>
<div id="layoutSidenav">

    {% include 'adminapp/includes/admin-sidebar.html' %}

    <div id="layoutSidenav_content">
        {% block content %}
        {% endblock %}
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2020</div>
                </div>
            </div>
        </footer>
    </div>
</div>
<!--<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>-->
<script src="https://code.jquery.com/jquery-3.6.0.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'js/auth-admin.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
<script src="{% static 'js/datatable.js' %}"></script>
<script src="{% static 'js/jquery.formset.js' %}"></script>
<script src="{% static 'js/orders_script.js' %}"></script>
</body>
</html>